export const text = {
  brand: 'dispensa',
  tagline: 'Meno pensieri, più cose buone.',
  recipes: 'Ricette',
  presets: 'Preset',
  local: 'Salvato su questo dispositivo',
  intro: 'La tua cucina, organizzata.',
  recipeIntro: 'Raccogli i piatti che ami. La prossima spesa parte da qui.',
  presetIntro: 'Metti insieme le ricette e prepara la spesa in un gesto.',
  newRecipe: 'Nuova ricetta',
  importCsv: 'Importa CSV',
  exportCsv: 'Esporta CSV',
  editRecipe: 'Modifica ricetta',
  baseRecipe: 'Ricetta base',
  newPreset: 'Nuovo preset',
  emptyRecipes: 'La prima ricetta è un buon inizio.',
  emptyRecipesBody:
    'Ingredienti, preparazione e un’icona: tutto quello che serve per ritrovarla.',
  emptyPresets: 'Un menu, una sola lista.',
  emptyPresetsBody: 'Crea un preset per la settimana o per una cena speciale.',
  name: 'Nome',
  icon: 'Icona',
  recipePlaceholder: 'Es. Pasta al pomodoro',
  presetPlaceholder: 'Es. Cene della settimana',
  ingredients: 'Ingredienti',
  preparation: 'Preparazione',
  ingredient: 'Ingrediente',
  quantity: 'Quantità',
  unit: 'Unità',
  optional: 'facoltativa',
  addIngredient: 'Aggiungi ingrediente',
  addStep: 'Aggiungi step',
  insertList: 'Inserisci elenco',
  convertList: 'Converti elenco',
  ingredientList: 'Elenco ingredienti',
  ingredientListPlaceholder:
    '- Pomodori q=4\n- Mozzarella q=250 u=g\n- Basilico',
  stepList: 'Elenco preparazione',
  stepListPlaceholder: '- Taglia gli ingredienti\n- Cuoci e servi',
  step: 'Step',
  saveRecipe: 'Salva ricetta',
  savePreset: 'Salva preset',
  cancel: 'Annulla',
  close: 'Chiudi',
  edit: 'Modifica',
  remove: 'Rimuovi',
  delete: 'Elimina',
  rename: 'Rinomina',
  deleteRecipe: 'Eliminare questa ricetta? Verrà rimossa anche dai preset.',
  deletePreset: 'Eliminare questo preset?',
  chooseRecipes: 'Componi il tuo menu',
  chooseBody: 'Seleziona le ricette. Apri i dettagli per scegliere con calma.',
  noSelection: 'Nessuna ricetta selezionata',
  noRecipes: 'Crea prima una ricetta nella tab Ricette.',
  shopping: 'Lista della spesa',
  shoppingEmpty: 'Aggiungi una ricetta per generare la lista.',
  copy: 'Copia lista',
  copied: 'Lista copiata!',
  copyError: 'Copia non riuscita. Seleziona e copia il testo qui sotto.',
  storageReadError:
    'Non è stato possibile leggere i dati salvati. Ricarica la pagina o salva nuovi dati per sostituirli.',
  storageWriteError:
    'Salvataggio locale non riuscito. Le modifiche restano aperte qui: riprova prima di chiudere la pagina.',
  baseRecipesReadError:
    'Le ricette base non sono disponibili. Controlla il file base_recipes.csv.',
  recipeImportError:
    'Importazione non riuscita. Usa le colonne nome, ingredienti e steps con liste Markdown valide.',
  recipeExportError: 'Esportazione CSV non riuscita. Riprova.',
  invalidQuantity: 'Inserisci una quantità numerica maggiore o uguale a zero.',
  invalidStep: 'Scrivi il testo di ogni step di preparazione.',
  invalidMarkdownList:
    'Inserisci una voce per riga, iniziando con -, * oppure +.',
  invalidIngredientList:
    'Controlla le annotazioni: usa una sola quantità q=numero e una sola unità u=testo per ingrediente.',
  navigation: 'Navigazione principale',
  editPreset: 'Modifica preset',
  retrySave: 'Riprova salvataggio',
  recipeCount: (count: number) =>
    `${count} ${count === 1 ? 'ricetta' : 'ricette'}`,
  presetCount: (count: number) => `${count} preset`,
  ingredientCount: (count: number) => `${count} ingredienti`,
  selected: (count: number) =>
    `${count} ${count === 1 ? 'selezionata' : 'selezionate'}`,
  recipeQuantity: (name: string) => `Quantità di ${name}`,
  addRecipe: (name: string) => `Aggiungi una selezione di ${name}`,
  removeRecipe: (name: string) => `Rimuovi una selezione di ${name}`,
  details: (name: string) => `Dettagli di ${name}`,
  removeIngredient: (index: number) => `Rimuovi ingrediente ${index + 1}`,
  removeStep: (index: number) => `Rimuovi step ${index + 1}`,
}
